---

- name: collect hardware
  no_log: true
  set_fact: 
    __disk_config: "{{ __disk_config|default([]) + [{'disk': item.key, 'id': item.value.links.ids[0]}] }}"
  with_dict: "{{ ansible_devices }}"
  when: item.value.links.ids | length > 0
  tags: ['disk']

- name: create disk info
  set_fact:
    local_disks: "{{ local_disks|default([]) + [ item[0] | combine(item[1]) ] }}"
  no_log: true
  with_nested: 
    - "{{ disk_volumes }}"
    - "{{ __disk_config }}"
  when:
    - disk_volumes is defined
    - item[0].name in item[1].id
  tags: ['disk']
